FROM node:22.15.0-alpine3.21 as base

FROM base AS deps
WORKDIR /app
COPY package.json ./
RUN yarn --frozen-lockfile

FROM base AS build
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn build

FROM base AS runner
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY ./package.json ./package.json
COPY ./tmp ./tmp
RUN apk add --no-cache libreoffice ttf-freefont
CMD ["yarn", "start:prod"]